version: '3.4'

services:
  tiendaservicios.api.autor:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapiautor
    container_name: api-autor
    restart: always
    build:
      context: .
      dockerfile: TiendaServicios.Api.Autor/Dockerfile
  tiendaservicios.api.libro:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapilibro
    container_name: api-libro
    restart: always
    build:
      context: .
      dockerfile: TiendaServicios.Api.Libro/Dockerfile

  tiendaservicios.api.carritocompra:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapicarritocompra
    container_name: api-carritocompra
    restart: always
    build:
      context: .
      dockerfile: TiendaServicios.Api.CarritoCompra/Dockerfile

  tiendaservicios.api.gateway:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapigateway
    container_name: api-gateway
    restart: always
    build:
      context: .
      dockerfile: TiendaServicios.Api.Gateway/Dockerfile

networks:
  default:
    external:
      name: mired_network



